version: '3.8'

services:
  angular-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - workstation-network
    depends_on:
      - eureka-server

networks:
  workstation-network:
    driver: bridge
