services:
  angular-frontend:
    build:
      context: .        # <-- root of repo
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - workstation-network

networks:
  workstation-network:
    driver: bridge
