services:
  angular-frontend:
    build:
      context: ./frontend       # Path to your Angular project
      dockerfile: Dockerfile    # Your Angular Dockerfile
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - workstation-network

networks:
  workstation-network:
    driver: bridge
